#!/bin/sh
#
# This a generated file. DO NOT EDIT THIS FILE!
# If you want to modify how this file works, please
# modify /home/mazzer/nors/install/nors.metainit and re-run update-metainit.
#
# If you are sure that you want to modify this file,
# remove this comment, and update-metainit will not override
# this script any more.
#
### BEGIN INIT INFO
# Provides:          nors
# Default-Start:     2 3 4 5
# Default-Stop:      1
# Short-Description: NORS
# Required-Start:   $syslog $time
# Required-Stop:     $syslog $time
# Description:       init script for nors-remote application.

### END INIT INFO


# Change DIR variable to suit where you install NORS
DIR=/home/mazzer/nors
PYTHON_PATH=$DIR/remote/:$DIR/models/:$DIR/server:$DIR:$DIR/remote/GrovePi/Software/Python/grove_barometer_sensors/barometric_sensor_bmp180/

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC=NORS
NAME=nors
PREPARE_ENV=$DIR/install/env_python_path.sh
DAEMON=$DIR/remote/nors.py
DAEMON_USER=root
BASENAME=nors.sh
DAEMON_ARGS=" -c /home/mazzer/nors/remote/nors.conf"
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME
# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 5

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
. /lib/lsb/init-functions

#
# Function that starts the daemon/service
#
do_start()
{
	echo "This is the Prestart-Hook";
	echo "It outputs two lines.";
#	start-stop-daemon --start --oknodo --background --quiet --make-pidfile --pidfile $PIDFILE --exec $DAEMON -- \
#	$PREPARE_ENV
	cd $DIR/remote
	export PYTHONPATH=$PYTHON_PATH
	start-stop-daemon --start --oknodo --make-pidfile --pidfile $PIDFILE --user $DAEMON_USER --chuid $DAEMON_USER --exec $DAEMON -- $DAEMON_ARGS 
	log_end_msg $?
}

#
# Function that stops the daemon/service
#
do_stop()
{
	start-stop-daemon --stop --oknodo --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $BASENAME
	RETVAL="$?"

	rm -f $PIDFILE

	return $RETVAL
	echo "This is the Poststop-Hook";
	echo "All it does, is print this.";
	return "$RETVAL"
}

#
# Function that sends a SIGHUP to the daemon/service
#
do_reload() {
	start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE --name $NAME
	return 0
}

case "$1" in
  start)
	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
	do_start
    log_end_msg $?
	;;
  stop)
	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
	do_stop
    log_end_msg $?
	;;
  #reload|force-reload)
	#
	# If do_reload() is not implemented then leave this commented out
	# and leave 'force-reload' as an alias for 'restart'.
	#
	#log_daemon_msg "Reloading $DESC" "$NAME"
	#do_reload
	#log_end_msg $?
	#;;
  restart|force-reload)
	#
	# If the "reload" option is implemented then remove the
	# 'force-reload' alias
	#
	log_daemon_msg "Restarting $DESC" "$NAME"
	do_stop
	case "$?" in
	  0)
		do_start
        log_end_msg "$?"
		;;
	  *)
	  	# Failed to stop
		log_end_msg 1
		;;
	esac
	;;
  *)
	#echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
	echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload}" >&2
	exit 3
	;;
esac
